selection_metadata:
  script_name: random_selection.py
  selection_method: random
  execution_time:
    start: '2025-09-10T22:33:47.810381'
    end: '2025-09-10T22:47:24.648618'
    duration_seconds: 816.838237
selection_parameters:
  selection_percentage: 0.05
  seed: 42
  sample_percentage: 1.0
dataset_configuration:
  dataset_from: hf
  dataset_config:
    datasets: &id011 !!python/object:omegaconf.listconfig.ListConfig
      _metadata: !!python/object:omegaconf.base.ContainerMetadata
        ref_type: &id001 !!python/name:typing.Any ''
        object_type: &id007 !!python/name:builtins.list ''
        optional: true
        key: datasets
        flags: {}
        flags_root: false
        resolver_cache: !!python/object/apply:collections.defaultdict
        - &id002 !!python/name:builtins.dict ''
        key_type: &id008 !!python/name:builtins.int ''
        element_type: *id001
      _parent: &id010 !!python/object:omegaconf.dictconfig.DictConfig
        _metadata: !!python/object:omegaconf.base.ContainerMetadata
          ref_type: *id001
          object_type: *id002
          optional: true
          key: hf
          flags: {}
          flags_root: false
          resolver_cache: !!python/object/apply:collections.defaultdict
          - *id002
          key_type: *id001
          element_type: *id001
        _parent: &id004 !!python/object:omegaconf.dictconfig.DictConfig
          _metadata: !!python/object:omegaconf.base.ContainerMetadata
            ref_type: *id001
            object_type: *id002
            optional: true
            key: dataset
            flags: {}
            flags_root: false
            resolver_cache: !!python/object/apply:collections.defaultdict
            - *id002
            key_type: *id001
            element_type: *id001
          _parent: &id003 !!python/object:omegaconf.dictconfig.DictConfig
            _metadata: !!python/object:omegaconf.base.ContainerMetadata
              ref_type: *id001
              object_type: *id002
              optional: true
              key: null
              flags:
                struct: true
              flags_root: false
              resolver_cache: !!python/object/apply:collections.defaultdict
                args:
                - *id002
                dictitems:
                  now:
                    ? !!python/tuple
                    - '%Y-%m-%d'
                    : '2025-09-10'
                    ? !!python/tuple
                    - '%H-%M-%S'
                    : 22-33-47
              key_type: *id001
              element_type: *id001
            _parent: null
            _content:
              stage: !!python/object:omegaconf.nodes.AnyNode
                _metadata: !!python/object:omegaconf.base.Metadata
                  ref_type: *id001
                  object_type: null
                  optional: true
                  key: stage
                  flags: {}
                  flags_root: false
                  resolver_cache: !!python/object/apply:collections.defaultdict
                  - *id002
                _parent: *id003
                _val: random_selection
              dataset: *id004
              selection_percentage: !!python/object:omegaconf.nodes.AnyNode
                _metadata: !!python/object:omegaconf.base.Metadata
                  ref_type: *id001
                  object_type: null
                  optional: true
                  key: selection_percentage
                  flags: {}
                  flags_root: false
                  resolver_cache: !!python/object/apply:collections.defaultdict
                  - *id002
                _parent: *id003
                _val: 0.05
              seed: !!python/object:omegaconf.nodes.AnyNode
                _metadata: !!python/object:omegaconf.base.Metadata
                  ref_type: *id001
                  object_type: null
                  optional: true
                  key: seed
                  flags: {}
                  flags_root: false
                  resolver_cache: !!python/object/apply:collections.defaultdict
                  - *id002
                _parent: *id003
                _val: 42
              sample_percentage: !!python/object:omegaconf.nodes.AnyNode
                _metadata: !!python/object:omegaconf.base.Metadata
                  ref_type: *id001
                  object_type: null
                  optional: true
                  key: sample_percentage
                  flags: {}
                  flags_root: false
                  resolver_cache: !!python/object/apply:collections.defaultdict
                  - *id002
                _parent: *id003
                _val: 1.0
              output_filename: !!python/object:omegaconf.nodes.AnyNode
                _metadata: !!python/object:omegaconf.base.Metadata
                  ref_type: *id001
                  object_type: null
                  optional: true
                  key: output_filename
                  flags: {}
                  flags_root: false
                  resolver_cache: !!python/object/apply:collections.defaultdict
                  - *id002
                _parent: *id003
                _val: randomly_selected_data.jsonl
              logging: &id005 !!python/object:omegaconf.dictconfig.DictConfig
                _metadata: !!python/object:omegaconf.base.ContainerMetadata
                  ref_type: *id001
                  object_type: *id002
                  optional: true
                  key: logging
                  flags: {}
                  flags_root: false
                  resolver_cache: !!python/object/apply:collections.defaultdict
                  - *id002
                  key_type: *id001
                  element_type: *id001
                _parent: *id003
                _content:
                  verbose: !!python/object:omegaconf.nodes.AnyNode
                    _metadata: !!python/object:omegaconf.base.Metadata
                      ref_type: *id001
                      object_type: null
                      optional: true
                      key: verbose
                      flags: {}
                      flags_root: false
                      resolver_cache: !!python/object/apply:collections.defaultdict
                      - *id002
                    _parent: *id005
                    _val: false
          _content:
            dataset_from: !!python/object:omegaconf.nodes.AnyNode
              _metadata: !!python/object:omegaconf.base.Metadata
                ref_type: *id001
                object_type: null
                optional: true
                key: dataset_from
                flags: {}
                flags_root: false
                resolver_cache: !!python/object/apply:collections.defaultdict
                - *id002
              _parent: *id004
              _val: hf
            local: &id006 !!python/object:omegaconf.dictconfig.DictConfig
              _metadata: !!python/object:omegaconf.base.ContainerMetadata
                ref_type: *id001
                object_type: *id002
                optional: true
                key: local
                flags: {}
                flags_root: false
                resolver_cache: !!python/object/apply:collections.defaultdict
                - *id002
                key_type: *id001
                element_type: *id001
              _parent: *id004
              _content:
                data_dir: !!python/object:omegaconf.nodes.AnyNode
                  _metadata: !!python/object:omegaconf.base.Metadata
                    ref_type: *id001
                    object_type: null
                    optional: true
                    key: data_dir
                    flags: {}
                    flags_root: false
                    resolver_cache: !!python/object/apply:collections.defaultdict
                    - *id002
                  _parent: *id006
                  _val: dataset/train/processed
                dataset_names: &id009 !!python/object:omegaconf.listconfig.ListConfig
                  _metadata: !!python/object:omegaconf.base.ContainerMetadata
                    ref_type: *id001
                    object_type: *id007
                    optional: true
                    key: dataset_names
                    flags: {}
                    flags_root: false
                    resolver_cache: !!python/object/apply:collections.defaultdict
                    - *id002
                    key_type: *id008
                    element_type: *id001
                  _parent: *id006
                  _content:
                  - !!python/object:omegaconf.nodes.AnyNode
                    _metadata: !!python/object:omegaconf.base.Metadata
                      ref_type: *id001
                      object_type: null
                      optional: true
                      key: 0
                      flags: {}
                      flags_root: false
                      resolver_cache: !!python/object/apply:collections.defaultdict
                      - *id002
                    _parent: *id009
                    _val: cot
                  - !!python/object:omegaconf.nodes.AnyNode
                    _metadata: !!python/object:omegaconf.base.Metadata
                      ref_type: *id001
                      object_type: null
                      optional: true
                      key: 1
                      flags: {}
                      flags_root: false
                      resolver_cache: !!python/object/apply:collections.defaultdict
                      - *id002
                    _parent: *id009
                    _val: dolly
                  - !!python/object:omegaconf.nodes.AnyNode
                    _metadata: !!python/object:omegaconf.base.Metadata
                      ref_type: *id001
                      object_type: null
                      optional: true
                      key: 2
                      flags: {}
                      flags_root: false
                      resolver_cache: !!python/object/apply:collections.defaultdict
                      - *id002
                    _parent: *id009
                    _val: flan_v2
                  - !!python/object:omegaconf.nodes.AnyNode
                    _metadata: !!python/object:omegaconf.base.Metadata
                      ref_type: *id001
                      object_type: null
                      optional: true
                      key: 3
                      flags: {}
                      flags_root: false
                      resolver_cache: !!python/object/apply:collections.defaultdict
                      - *id002
                    _parent: *id009
                    _val: oasst1
            hf: *id010
        _content:
          datasets: *id011
      _content:
      - &id012 !!python/object:omegaconf.dictconfig.DictConfig
        _metadata: !!python/object:omegaconf.base.ContainerMetadata
          ref_type: *id001
          object_type: *id002
          optional: true
          key: 0
          flags: {}
          flags_root: false
          resolver_cache: !!python/object/apply:collections.defaultdict
          - *id002
          key_type: *id001
          element_type: *id001
        _parent: *id011
        _content:
          name: !!python/object:omegaconf.nodes.AnyNode
            _metadata: !!python/object:omegaconf.base.Metadata
              ref_type: *id001
              object_type: null
              optional: true
              key: name
              flags: {}
              flags_root: false
              resolver_cache: !!python/object/apply:collections.defaultdict
              - *id002
            _parent: *id012
            _val: teknium/OpenHermes-2.5
          dataset_name: !!python/object:omegaconf.nodes.AnyNode
            _metadata: !!python/object:omegaconf.base.Metadata
              ref_type: *id001
              object_type: null
              optional: true
              key: dataset_name
              flags: {}
              flags_root: false
              resolver_cache: !!python/object/apply:collections.defaultdict
              - *id002
            _parent: *id012
            _val: openhermes
          subset: !!python/object:omegaconf.nodes.AnyNode
            _metadata: !!python/object:omegaconf.base.Metadata
              ref_type: *id001
              object_type: null
              optional: true
              key: subset
              flags: {}
              flags_root: false
              resolver_cache: !!python/object/apply:collections.defaultdict
              - *id002
            _parent: *id012
            _val: null
          split: !!python/object:omegaconf.nodes.AnyNode
            _metadata: !!python/object:omegaconf.base.Metadata
              ref_type: *id001
              object_type: null
              optional: true
              key: split
              flags: {}
              flags_root: false
              resolver_cache: !!python/object/apply:collections.defaultdict
              - *id002
            _parent: *id012
            _val: train
output_paths:
  selected_data_path: /mnt/lishiwei/Select-moe/randomly_selected_data.jsonl
  output_filename: randomly_selected_data.jsonl
