# FSDP Configuration for Finetune Stage (Llama-2-7B)
# Optimized for LoRA fine-tuning with Llama-2-7B model

compute_environment: LOCAL_MACHINE
distributed_type: 'FSDP'
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: 'TRANSFORMER_BASED_WRAP'
  fsdp_backward_prefetch: 'BACKWARD_PRE'
  fsdp_cpu_ram_efficient_loading: false
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: 'FULL_SHARD'
  fsdp_state_dict_type: 'FULL_STATE_DICT'
  fsdp_sync_module_states: true
  fsdp_transformer_layer_cls_to_wrap: 'LlamaDecoderLayer'
  fsdp_use_orig_params: true
gpu_ids: 'all'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 1 # This will be overridden by --num_processes in the launch command
rdzv_backend: 'static'
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
