# @package _global_

# Batch Selection Configuration (批量数据筛选)
# 自动化批量处理多个实验的数据筛选

# Hydra Configuration
hydra:
  run:
    dir: outputs/batch_selection/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/batch_selection
    subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}

# Root directory to scan for experiments
root_dir: "outputs/stage_2_selection"

# Output directory for batch processing report
output_dir: ${hydra:run.dir}

# Data directory (optional, for loading original messages)
data_dir: null  # If not provided, will auto-infer

# Selection percentage (e.g., 0.30 means select top 30%)
selection_percentage: 0.25

# Quality scoring parameters
quality_params:
  alpha: 1.0      # token权重参数（默认1；>1 更偏重高熵；<1 更均衡）
  eps: 1.0e-8     # 数值下界，防分母为0
  tau: 0.0        # 稳定性参数（可选，0表示不使用）

# Batch processing configuration
batch_processing:
  skip_existing: true          # Skip directories that already have selected_data.jsonl
  dry_run: false               # If true, only show what would be processed
  continue_on_error: true      # Continue processing other experiments if one fails
  save_report: true            # Save detailed processing report

# Force processing configuration
force_processing:
  enabled: false               # Force reprocessing even if output exists
  backup_existing: true        # Backup existing files before overwriting

# Logging configuration
logging:
  verbose: false  # Enable debug logging
