# @package _global_

# Continue Selection Configuration (数据筛选阶段)
# 基于已收集的统计数据进行质量筛选

# Hydra Configuration
hydra:
  run:
    dir: outputs/continue_selection/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/continue_selection
    subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}

# Router data directory (from stage 2 selection)
router_data_dir: null  # Must be provided via command line

# Data directory (optional, for loading original messages)
data_dir: null  # If not provided, will auto-infer from router_data_dir

# Selection percentage (e.g., 0.30 means select top 30%)
selection_percentage: 0.30

# Quality scoring parameters
quality_params:
  alpha: 1.0      # token权重参数（默认1；>1 更偏重高熵；<1 更均衡）
  eps: 1.0e-8     # 数值下界，防分母为0
  tau: 0.0        # 稳定性参数（可选，0表示不使用）

# Logging configuration
logging:
  verbose: false  # Enable debug logging
