# @package _global_

stage: continue_selection

# Hydra settings to create a timestamped output directory
hydra:
  run:
    dir: outputs/continue_selection/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/continue_selection
    subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    config:
      override_dirname:
        kv_sep: "="
        item_sep: ","
        exclude_keys:
          - hydra.run.dir
          - hydra.sweep.dir
          - hydra.sweep.subdir

# Required: Directory containing router_data files
# Example: outputs/stage_2_selection/2025-08-11/03-52-40-batch=8_lr=0.001_loss=beta_moment_matching_tag=none/router_data
router_data_dir: "outputs/stage_2_selection/2025-08-11/03-52-40-batch=8_lr=0.0003_loss=sigmoid_tag=none/router_data"

# Data selection percentage (0.05 means select top 5% of the data)
selection_percentage: 0.05

# Optional: Original dataset directory path (auto-inferred if not specified)
data_dir: null

# Clustering method: currently only "kmeans" is supported
clustering_method: "kmeans"

# Clustering parameters
clustering_params:
  # K-Means specific parameters
  auto_k: false  # Automatically determine k using Elbow method
  k: 26  # Manual k value (only used if auto_k=false)
  k_range: [20, 100]  # k search range for Elbow method
  max_iters: 300  # Maximum iterations
  
  # K-Means parallel computation parameters
  enable_parallel_kmeans: true  # Enable multi-GPU parallel computation for k-value search
  parallel_processes: 7  # Number of parallel processes for k-value computation
  gpu_allocation_strategy: "round_robin"  # GPU allocation strategy: "round_robin" or "balanced"

# Device configuration
device: "auto"  # "cuda", "cpu", or "auto" for automatic detection

# Debug configuration
debug_print: false  # Enable detailed debug output for clustering algorithms

# Logging configuration
logging:
  verbose: false  # Enable detailed logging output