# @package _global_

# Stage 2: Data Selection Configuration

# Path to the pretrained model from stage 1
model_checkpoint_path: "outputs/2025-06-15/11-59-04/stage_1_pretrain"

# Datasets to be scored and filtered.
# This uses the same structure as stage_1_pretrain for consistency.
dataset:
  paths:
    - databricks/databricks-dolly-15k
  seed: 42
  # To speed up the selection process, we can score a subset of the combined dataset.
  # 1.0 means using the full dataset.
  subset_ratio: 0.1 # Use full dataset for dolly

# The ratio of experts to be considered as "trash" experts.
# For a model with 8 experts, 0.125 means 1 expert is the trash can.
trash_expert_ratio: 0.125

# The percentage of data to select based on quality score.
# 0.05 means the top 5% of the data will be selected.
selection_percentage: 0.05

# The output filename.
output_filename: "selected_data.jsonl"

# The full path to save the filtered dataset.
# This will be inside the timestamped Hydra run directory.
output_path: "${hydra.run.dir}/${output_filename}"

# Data processing settings
data_process:
  batch_size: 8