# @package _global_

# Stage 1: Pre-training Configuration

# Hydra settings
hydra:
  run:
    dir: outputs/stage_1_pretrain/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Model configuration
selector_model:
  name: "allenai/OLMoE-1B-7B-0125"
output_dir: ${hydra:run.dir}

# Dataset configuration
dataset:
  paths:
    - "teknium/OpenHermes-2.5"
    - "allenai/WildChat-1M"
  subset_ratio: 0.001
  seed: 42
  max_length: 512

# Training configuration
training:
  batch_size: 4
  learning_rate: 1e-4
  epochs: 1
  optimizer: "AdamW"
  scheduler: "linear"