defaults:
  - _self_

eval:
  model:
    pretrained: meta-llama/Llama-2-7b-hf
    peft: outputs/stage_3_finetune/2025-07-18/01-01-10/checkpoint-1804
  tasks:
    - mmlu
  batch_size: auto
  device: "cuda:1"

output:
  results_path: ${hydra:run.dir}/evaluation_results.json