# @package _global_

stage: selection

# 模型配置
selector_model:
  path: "converted_models/select_moe_converted_OLMoE-1B-7B-0125"
  tokenizer_name: "allenai/OLMoE-1B-7B-0125"

# Stage 2: Data Selection Configuration

# Hydra settings to create a timestamped output directory, similar to stage 1
hydra:
  run:
    dir: outputs/stage_2_selection/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Path to the full rank weights from stage 1
model_checkpoint_path: "outputs/stage_1_pretrain/2025-07-16/01-57-27/full_rank_weights.pt"

# The final output path for the selected data.
# It uses the Hydra-generated run directory.
output_path: "${hydra:run.dir}/selected_data.jsonl"

# Dataset configuration - 使用与stage 1相同的4个数据集
dataset:
  data_dir: "dataset/train/processed"
  dataset_names:
    - "cot"
    - "dolly"
    - "flan_v2"
    - "oasst1"
  seed: 42
  shuffle: false
  max_sequence_length: 1024
  # To speed up the selection process, we can score a subset of the combined dataset.
  # 1.0 means using the full dataset.
  subset_ratio: 1 

# The percentage of data to select based on quality score.
# 0.05 means the top 5% of the data will be selected.
selection_percentage: 0.05

# Data processing settings
data_process:
  batch_size: 64